from __future__ import annotations

from datetime import datetime
from typing import Protocol

from notifications.application.dto import AttendanceCandidate, TargetResolution, TaskCandidate


class TaskFactsPort(Protocol):
    def due_upcoming(self, now: datetime) -> tuple[TaskCandidate, ...]: ...
    def due_overdue(self, now: datetime) -> tuple[TaskCandidate, ...]: ...
    def revalidate(self, task_id: int, recipient_id: int, event_type: str) -> bool: ...
    def resolve(self, actor_id: int, task_id: int) -> TargetResolution | None: ...


class AttendanceFactsPort(Protocol):
    def due_open_sessions(self, now: datetime) -> tuple[AttendanceCandidate, ...]: ...
    def revalidate(self, session_id: int, recipient_id: int, event_type: str) -> bool: ...
    def resolve(self, actor_id: int, session_id: int) -> TargetResolution | None: ...


class OccurrenceSink(Protocol):
    def record(self, occurrence: object) -> object: ...
    def suppress(
        self, target_type: str, target_id: int, recipient_ids: tuple[int, ...] = ()
    ) -> int: ...
