# Generated by Django 5.2.5 on 2026-08-17 18:36

import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('LEADER', 'LEADER'), ('MANAGER', 'MANAGER'), ('HELPDESK', 'HELPDESK')], max_length=16)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('must_change_password', models.BooleanField(db_default=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('username__regex', '^\\s*$'), _negated=True), name='identity_user_username_nonblank'), models.CheckConstraint(condition=models.Q(('full_name__regex', '^\\s*$'), _negated=True), name='identity_user_full_name_nonblank'), models.CheckConstraint(condition=models.Q(('role__in', ['LEADER', 'MANAGER', 'HELPDESK'])), name='identity_user_role_valid')],
            },
            managers=[
                ('objects', identity.models.UserManager()),
            ],
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION identity_reject_username_change() RETURNS trigger AS $$
            BEGIN
                IF NEW.username IS DISTINCT FROM OLD.username THEN
                    RAISE EXCEPTION 'identity username is immutable';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER identity_user_username_immutable
            BEFORE UPDATE ON identity_user
            FOR EACH ROW EXECUTE FUNCTION identity_reject_username_change();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS identity_user_username_immutable ON identity_user;
            DROP FUNCTION IF EXISTS identity_reject_username_change();
            """,
        ),
    ]
