VALIDATION_FAILED = "VALIDATION_FAILED"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
INVALID_TOKEN = "INVALID_TOKEN"
ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
PASSWORD_CHANGE_REQUIRED = "PASSWORD_CHANGE_REQUIRED"
SERVER_OWNED_FIELD = "SERVER_OWNED_FIELD"
NOT_FOUND = "NOT_FOUND"
LOCATION_VERSION_CONFLICT = "LOCATION_VERSION_CONFLICT"
THROTTLED = "THROTTLED"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
WEAK_GPS = "WEAK_GPS"
OUTSIDE_RADIUS = "OUTSIDE_RADIUS"
LOCATION_CHOICE_REQUIRED = "LOCATION_CHOICE_REQUIRED"
INVALID_LOCATION_CHOICE = "INVALID_LOCATION_CHOICE"
NO_OPEN_SESSION = "NO_OPEN_SESSION"
SESSION_ALREADY_OPEN = "SESSION_ALREADY_OPEN"
INACTIVE_ASSIGNEE = "INACTIVE_ASSIGNEE"
BLOCK_REASON_REQUIRED = "BLOCK_REASON_REQUIRED"
TASK_ALREADY_COMPLETED = "TASK_ALREADY_COMPLETED"
EVIDENCE_UPLOAD_INVALID = "EVIDENCE_UPLOAD_INVALID"
EVIDENCE_UPLOAD_NOT_READY = "EVIDENCE_UPLOAD_NOT_READY"
IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"

AUTHORIZED_FOUNDATION_ERROR_CODES = frozenset(
    {
        VALIDATION_FAILED,
        PERMISSION_DENIED,
        INVALID_CREDENTIALS,
        INVALID_TOKEN,
        ACCOUNT_INACTIVE,
        PASSWORD_CHANGE_REQUIRED,
        SERVER_OWNED_FIELD,
        NOT_FOUND,
        LOCATION_VERSION_CONFLICT,
        THROTTLED,
        SERVICE_UNAVAILABLE,
        WEAK_GPS,
        OUTSIDE_RADIUS,
        LOCATION_CHOICE_REQUIRED,
        INVALID_LOCATION_CHOICE,
        NO_OPEN_SESSION,
        SESSION_ALREADY_OPEN,
        INACTIVE_ASSIGNEE,
        BLOCK_REASON_REQUIRED,
        TASK_ALREADY_COMPLETED,
        EVIDENCE_UPLOAD_INVALID,
        EVIDENCE_UPLOAD_NOT_READY,
        IDEMPOTENCY_CONFLICT,
    }
)
