VALIDATION_FAILED = "VALIDATION_FAILED"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
INVALID_TOKEN = "INVALID_TOKEN"
ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
PASSWORD_CHANGE_REQUIRED = "PASSWORD_CHANGE_REQUIRED"
SERVER_OWNED_FIELD = "SERVER_OWNED_FIELD"
NOT_FOUND = "NOT_FOUND"
LOCATION_VERSION_CONFLICT = "LOCATION_VERSION_CONFLICT"

AUTHORIZED_FOUNDATION_ERROR_CODES = frozenset(
    {
        VALIDATION_FAILED,
        PERMISSION_DENIED,
        INVALID_CREDENTIALS,
        INVALID_TOKEN,
        ACCOUNT_INACTIVE,
        PASSWORD_CHANGE_REQUIRED,
        SERVER_OWNED_FIELD,
        NOT_FOUND,
        LOCATION_VERSION_CONFLICT,
    }
)
