from typing import Protocol


class AttendanceAuthorization(Protocol):
    def authorize_check_in(self, actor_id: int) -> None: ...
    def authorize_check_out(self, actor_id: int) -> None: ...
    def authorize_view_self(self, actor_id: int) -> None: ...
