from datetime import date
from decimal import Decimal
from typing import Protocol

from attendance.application.dto import AcceptedPunchRequest, AttendanceSnapshot, SessionProjection
from attendance.domain.attendance import AttendanceAnomalyReason
from attendance.domain.sessions import SessionSnapshot


class AttendanceRepository(Protocol):
    def open_session(self, user_id: int, *, lock: bool = False) -> SessionSnapshot | None: ...
    def create_attendance(self, request: AcceptedPunchRequest) -> AttendanceSnapshot: ...
    def open_new_session(self, attendance: AttendanceSnapshot) -> SessionProjection: ...
    def close_session(
        self, session: SessionSnapshot, attendance: AttendanceSnapshot
    ) -> SessionProjection: ...
    def punches(self, user_id: int, work_date: date) -> tuple[AttendanceSnapshot, ...]: ...
    def sessions(self, user_id: int, work_date: date) -> tuple[SessionProjection, ...]: ...
    def replace_anomalies(
        self, attendance_id: int, reasons: tuple[AttendanceAnomalyReason, ...]
    ) -> None: ...
    def total_duration(self, user_id: int, work_date: date) -> Decimal: ...
