/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/attendance/check-in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["attendance_check_in"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/attendance/check-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["attendance_check_out"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/attendance/today": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["attendance_today_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_login_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_logout_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["auth_refresh_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/change-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["identity_change_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/config/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["config_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["config_partial_update"];
    trace?: never;
  };
  "/api/v1/holidays/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["holidays_list"];
    put?: never;
    post: operations["holidays_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/holidays/{holiday_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["holidays_destroy"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/locations/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["locations_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/locations/{location_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["locations_partial_update"];
    trace?: never;
  };
  "/api/v1/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["identity_me_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["identity_me_partial_update"];
    trace?: never;
  };
  "/api/v1/schema/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Machine-readable schema endpoint; no interactive UI is registered. */
    get: operations["api_schema_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["users_list"];
    put?: never;
    post: operations["users_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["users_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["users_partial_update"];
    trace?: never;
  };
  "/api/v1/users/{user_id}/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["users_reset_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["users_role_partial_update"];
    trace?: never;
  };
  "/api/v1/users/{user_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["users_status_partial_update"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AccessResponse: {
      readonly access: string;
    };
    AdminUser: {
      /** Format: date-time */
      readonly created_at: string;
      /** Format: email */
      readonly email: string | null;
      readonly full_name: string;
      readonly id: number;
      readonly is_active: boolean;
      /** Format: date-time */
      readonly last_login: string | null;
      readonly must_change_password: boolean;
      readonly phone: string | null;
      readonly role: string;
      readonly username: string;
    };
    AttendanceCommand: {
      /** Format: decimal */
      accuracy_m: string;
      /** Format: date-time */
      captured_at?: string | null;
      /** Format: decimal */
      latitude: string;
      /** Format: decimal */
      longitude: string;
      selected_location_id?: number | null;
    };
    AttendanceCommandResult: {
      readonly attendance: components["schemas"]["AttendancePunch"];
      readonly punch_index: number;
      readonly session: components["schemas"]["AttendanceSession"];
    };
    AttendanceError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: string;
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    AttendanceLocation: {
      readonly address: string;
      readonly code: string;
      readonly id: number;
      readonly name: string;
    };
    AttendancePunch: {
      /** Format: decimal */
      readonly accuracy_m: string;
      /** Format: date-time */
      readonly captured_at: string | null;
      /** Format: decimal */
      readonly captured_latitude: string;
      /** Format: decimal */
      readonly captured_longitude: string;
      /** Format: decimal */
      readonly distance_m: string;
      readonly id: number;
      readonly kind: string;
      readonly location: components["schemas"]["AttendanceLocation"];
      readonly maps_url: string;
      /** Format: date-time */
      readonly recorded_at: string;
      readonly resolution_method: string;
      readonly resolved_address: string;
      readonly validation_result: string;
      /** Format: date */
      readonly work_date: string;
    };
    AttendanceSession: {
      /** Format: date-time */
      readonly check_in_at: string;
      readonly check_in_location_id: number;
      /** Format: date-time */
      readonly check_out_at: string | null;
      readonly check_out_location_id: number | null;
      readonly closed_by_job: boolean;
      /** Format: decimal */
      readonly duration_minutes: string | null;
      readonly id: number;
      /** Format: date */
      readonly work_date: string;
    };
    AttendanceUnprocessableError:
      | components["schemas"]["GpsBoundaryError"]
      | components["schemas"]["InvalidLocationChoiceError"];
    CheckInConflictError:
      | components["schemas"]["SessionAlreadyOpenError"]
      | components["schemas"]["LocationChoiceRequiredError"];
    CheckOutConflictError:
      | components["schemas"]["NoOpenSessionError"]
      | components["schemas"]["LocationChoiceRequiredError"];
    /** @enum {string} */
    CodeEnum: "GEOFENCE_OVERLAP" | "RADIUS_BELOW_ATTENDANCE_ACCURACY";
    Config: {
      /** Format: decimal */
      readonly default_radius_m: string;
      readonly early_checkout_grace_minutes: number;
      readonly id: number;
      readonly late_checkout_grace_minutes: number;
      readonly late_grace_minutes: number;
      /** Format: decimal */
      readonly max_attendance_accuracy_m: string;
      /** Format: decimal */
      readonly max_radius_m: string;
      /** Format: time */
      readonly shift_end: string;
      /** Format: time */
      readonly shift_start: string;
      /** Format: decimal */
      readonly task_gps_good_accuracy_m: string;
      /** Format: decimal */
      readonly task_gps_low_accuracy_m: string;
      readonly timezone: string;
      readonly working_weekdays: number[];
    };
    ConfigUpdate: {
      /** Format: decimal */
      default_radius_m?: string;
      early_checkout_grace_minutes?: number;
      late_checkout_grace_minutes?: number;
      late_grace_minutes?: number;
      /** Format: decimal */
      max_attendance_accuracy_m?: string;
      /** Format: decimal */
      max_radius_m?: string;
      /** Format: time */
      shift_end?: string;
      /** Format: time */
      shift_start?: string;
      /** Format: decimal */
      task_gps_good_accuracy_m?: string;
      /** Format: decimal */
      task_gps_low_accuracy_m?: string;
      working_weekdays?: number[];
    };
    ConfigUpdateResult: {
      readonly config: components["schemas"]["Config"];
      readonly warnings: components["schemas"]["Warning"][];
    };
    FoundationError: {
      details: {
        [key: string]: string[];
      };
      /** @deprecated */
      error: string;
      /** @description Governance-authorized error code. */
      error_code: string;
      message: string;
      /** Format: uuid */
      request_id: string;
    };
    GeneratedUserResult: {
      readonly generated_password: string;
      readonly user: components["schemas"]["AdminUser"];
    };
    GpsBoundaryError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: components["schemas"]["GpsBoundaryErrorErrorCodeEnum"];
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    /** @enum {string} */
    GpsBoundaryErrorErrorCodeEnum: "WEAK_GPS" | "OUTSIDE_RADIUS";
    Holiday: {
      /** Format: date */
      readonly date: string;
      readonly id: number;
      readonly name: string;
    };
    HolidayCreate: {
      /** Format: date */
      date: string;
      name: string;
    };
    IdentityError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: string;
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    IndexedAttendancePunch: {
      /** Format: decimal */
      readonly accuracy_m: string;
      /** Format: date-time */
      readonly captured_at: string | null;
      /** Format: decimal */
      readonly captured_latitude: string;
      /** Format: decimal */
      readonly captured_longitude: string;
      /** Format: decimal */
      readonly distance_m: string;
      readonly id: number;
      readonly kind: string;
      readonly location: components["schemas"]["AttendanceLocation"];
      readonly maps_url: string;
      readonly punch_index: number;
      /** Format: date-time */
      readonly recorded_at: string;
      readonly resolution_method: string;
      readonly resolved_address: string;
      readonly validation_result: string;
      /** Format: date */
      readonly work_date: string;
    };
    InvalidLocationChoiceError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: components["schemas"]["InvalidLocationChoiceErrorErrorCodeEnum"];
      readonly location_candidates: components["schemas"]["LocationCandidate"][];
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    /** @enum {string} */
    InvalidLocationChoiceErrorErrorCodeEnum: "INVALID_LOCATION_CHOICE";
    Location: {
      readonly address: string;
      readonly code: string;
      readonly id: number;
      readonly is_active: boolean;
      readonly kind: string;
      /** Format: decimal */
      readonly latitude: string;
      /** Format: decimal */
      readonly longitude: string;
      readonly name: string;
      readonly parent_code: string | null;
      readonly parent_id: number | null;
      /** Format: decimal */
      readonly radius_m: string;
      readonly version: number;
    };
    LocationCandidate: {
      readonly code: string;
      /** Format: decimal */
      readonly distance_m: string;
      readonly id: number;
      readonly name: string;
    };
    LocationChoiceRequiredError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: components["schemas"]["LocationChoiceRequiredErrorErrorCodeEnum"];
      readonly location_candidates: components["schemas"]["LocationCandidate"][];
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    /** @enum {string} */
    LocationChoiceRequiredErrorErrorCodeEnum: "LOCATION_CHOICE_REQUIRED";
    LocationUpdate: {
      address?: string;
      is_active?: boolean;
      /** Format: decimal */
      latitude?: string;
      /** Format: decimal */
      longitude?: string;
      name?: string;
      /** Format: decimal */
      radius_m?: string;
      reason?: string;
      version: number;
    };
    LocationUpdateResult: {
      readonly location: components["schemas"]["Location"];
      readonly warnings: components["schemas"]["Warning"][];
    };
    Login: {
      password: string;
      username: string;
    };
    LoginResponse: {
      readonly access: string;
      readonly capabilities: string[];
      readonly is_active: boolean;
      readonly must_change_password: boolean;
      readonly role: string;
    };
    NoOpenSessionError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: components["schemas"]["NoOpenSessionErrorErrorCodeEnum"];
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    /** @enum {string} */
    NoOpenSessionErrorErrorCodeEnum: "NO_OPEN_SESSION";
    PasswordChange: {
      current_password: string;
      new_password: string;
    };
    Profile: {
      /** Format: email */
      email?: string | null;
      full_name?: string;
      phone?: string | null;
    };
    ResetPasswordResult: {
      readonly generated_password: string;
      readonly must_change_password: boolean;
      readonly user_id: number;
    };
    Role: {
      role: string;
    };
    SelfUser: {
      readonly capabilities: string[];
      /** Format: date-time */
      readonly created_at: string;
      /** Format: email */
      readonly email: string | null;
      readonly full_name: string;
      readonly id: number;
      readonly is_active: boolean;
      /** Format: date-time */
      readonly last_login: string | null;
      readonly must_change_password: boolean;
      readonly phone: string | null;
      readonly role: string;
      readonly username: string;
    };
    SessionAlreadyOpenError: {
      readonly details: {
        [key: string]: unknown;
      };
      readonly error: string;
      readonly error_code: components["schemas"]["SessionAlreadyOpenErrorErrorCodeEnum"];
      readonly message: string;
      /** Format: uuid */
      readonly request_id: string;
    };
    /** @enum {string} */
    SessionAlreadyOpenErrorErrorCodeEnum: "SESSION_ALREADY_OPEN";
    Status: {
      is_active: boolean;
    };
    TodayAttendance: {
      readonly has_open_session: boolean;
      readonly punches: components["schemas"]["IndexedAttendancePunch"][];
      readonly sessions: components["schemas"]["AttendanceSession"][];
      /** Format: decimal */
      readonly total_duration_minutes: string;
      /** Format: date */
      readonly work_date: string;
    };
    UserCreate: {
      /** Format: email */
      email?: string | null;
      full_name: string;
      phone?: string | null;
      role: string;
      username: string;
    };
    UserPage: {
      readonly count: number;
      readonly next: string | null;
      readonly previous: string | null;
      readonly results: components["schemas"]["AdminUser"][];
    };
    Warning: {
      readonly code: components["schemas"]["CodeEnum"];
      /** Format: decimal */
      radius_m?: string;
      related_location_codes?: string[];
      related_location_ids?: number[];
      /** Format: decimal */
      threshold_m?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  attendance_check_in: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceCommand"];
        "application/x-www-form-urlencoded": components["schemas"]["AttendanceCommand"];
        "multipart/form-data": components["schemas"]["AttendanceCommand"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceCommandResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckInConflictError"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceUnprocessableError"];
        };
      };
    };
  };
  attendance_check_out: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceCommand"];
        "application/x-www-form-urlencoded": components["schemas"]["AttendanceCommand"];
        "multipart/form-data": components["schemas"]["AttendanceCommand"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceCommandResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceError"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckOutConflictError"];
        };
      };
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AttendanceUnprocessableError"];
        };
      };
    };
  };
  attendance_today_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TodayAttendance"];
        };
      };
    };
  };
  auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
        "application/x-www-form-urlencoded": components["schemas"]["Login"];
        "multipart/form-data": components["schemas"]["Login"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  auth_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  identity_change_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccessResponse"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  config_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Config"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  config_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ConfigUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["ConfigUpdate"];
        "multipart/form-data": components["schemas"]["ConfigUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigUpdateResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  holidays_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Holiday"][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  holidays_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HolidayCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["HolidayCreate"];
        "multipart/form-data": components["schemas"]["HolidayCreate"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Holiday"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  holidays_destroy: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        holiday_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  locations_list: {
    parameters: {
      query?: {
        is_active?: boolean;
        kind?: "BUSINESS_CENTER" | "SHOP";
        parent?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Location"][];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  locations_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        location_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocationUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["LocationUpdate"];
        "multipart/form-data": components["schemas"]["LocationUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LocationUpdateResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FoundationError"];
        };
      };
    };
  };
  identity_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SelfUser"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  identity_me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Profile"];
        "application/x-www-form-urlencoded": components["schemas"]["Profile"];
        "multipart/form-data": components["schemas"]["Profile"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SelfUser"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  api_schema_retrieve: {
    parameters: {
      query?: {
        format?: "json" | "yaml";
        lang?:
          | "af"
          | "ar"
          | "ar-dz"
          | "ast"
          | "az"
          | "be"
          | "bg"
          | "bn"
          | "br"
          | "bs"
          | "ca"
          | "ckb"
          | "cs"
          | "cy"
          | "da"
          | "de"
          | "dsb"
          | "el"
          | "en"
          | "en-au"
          | "en-gb"
          | "eo"
          | "es"
          | "es-ar"
          | "es-co"
          | "es-mx"
          | "es-ni"
          | "es-ve"
          | "et"
          | "eu"
          | "fa"
          | "fi"
          | "fr"
          | "fy"
          | "ga"
          | "gd"
          | "gl"
          | "he"
          | "hi"
          | "hr"
          | "hsb"
          | "hu"
          | "hy"
          | "ia"
          | "id"
          | "ig"
          | "io"
          | "is"
          | "it"
          | "ja"
          | "ka"
          | "kab"
          | "kk"
          | "km"
          | "kn"
          | "ko"
          | "ky"
          | "lb"
          | "lt"
          | "lv"
          | "mk"
          | "ml"
          | "mn"
          | "mr"
          | "ms"
          | "my"
          | "nb"
          | "ne"
          | "nl"
          | "nn"
          | "os"
          | "pa"
          | "pl"
          | "pt"
          | "pt-br"
          | "ro"
          | "ru"
          | "sk"
          | "sl"
          | "sq"
          | "sr"
          | "sr-latn"
          | "sv"
          | "sw"
          | "ta"
          | "te"
          | "tg"
          | "th"
          | "tk"
          | "tr"
          | "tt"
          | "udm"
          | "ug"
          | "uk"
          | "ur"
          | "uz"
          | "vi"
          | "zh-hans"
          | "zh-hant";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
          "application/vnd.oai.openapi": {
            [key: string]: unknown;
          };
          "application/vnd.oai.openapi+json": {
            [key: string]: unknown;
          };
          "application/yaml": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  users_list: {
    parameters: {
      query?: {
        is_active?: boolean;
        page?: number;
        q?: string;
        role?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPage"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["UserCreate"];
        "multipart/form-data": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeneratedUserResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUser"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["Profile"];
        "application/x-www-form-urlencoded": components["schemas"]["Profile"];
        "multipart/form-data": components["schemas"]["Profile"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUser"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_reset_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResetPasswordResult"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_role_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Role"];
        "application/x-www-form-urlencoded": components["schemas"]["Role"];
        "multipart/form-data": components["schemas"]["Role"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUser"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
  users_status_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Status"];
        "application/x-www-form-urlencoded": components["schemas"]["Status"];
        "multipart/form-data": components["schemas"]["Status"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUser"];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IdentityError"];
        };
      };
    };
  };
}
