# Generated by Codex for Feature 013 observability

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_job_run"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_name", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job_name", "updated_at"],
                        name="job_heartbeat_updated_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_name",),
                        name="job_heartbeat_name_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("outcome__in", ["ok", "failed", "running"])),
                        name="job_heartbeat_outcome_valid",
                    ),
                ],
            },
        ),
    ]
