from __future__ import annotations

from datetime import date
from typing import Protocol

from locations.domain.config import ConfigSnapshot
from locations.domain.holidays import HolidaySnapshot
from locations.domain.locations import LocationCandidate, LocationSnapshot


class LocationRepository(Protocol):
    def list(
        self,
        *,
        kind: str | None = None,
        parent_id: int | None = None,
        is_active: bool | None = None,
    ) -> tuple[LocationSnapshot, ...]: ...
    def get(self, location_id: int, *, lock: bool = False) -> LocationSnapshot | None: ...
    def all_by_code(self, *, lock: bool = False) -> dict[str, LocationSnapshot]: ...
    def create_source(self, values: dict[str, object]) -> LocationSnapshot: ...
    def reconcile_source(
        self, code: str, values: dict[str, object], version: int
    ) -> LocationSnapshot: ...
    def set_parent(self, code: str, parent_code: str | None) -> LocationSnapshot: ...
    def update(
        self, location_id: int, candidate: LocationCandidate, version: int
    ) -> LocationSnapshot: ...


class ConfigRepository(Protocol):
    def get(self, *, lock: bool = False) -> ConfigSnapshot | None: ...
    def create(self, config: ConfigSnapshot) -> ConfigSnapshot: ...
    def update(self, config: ConfigSnapshot) -> ConfigSnapshot: ...


class HolidayRepository(Protocol):
    def list(self) -> tuple[HolidaySnapshot, ...]: ...
    def create(self, value_date: date, name: str) -> HolidaySnapshot: ...
    def get(self, holiday_id: int, *, lock: bool = False) -> HolidaySnapshot | None: ...
    def delete(self, holiday_id: int) -> None: ...
