# Generated by Django 5.2.5 on 2026-08-20

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, default="")),
                ("assigned_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "TODO"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("BLOCKED", "BLOCKED"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        db_default="TODO",
                        default="TODO",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANAGER_OVERRIDE", "MANAGER_OVERRIDE"),
                            ("FIELD_EVIDENCE", "FIELD_EVIDENCE"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("completion_note", models.TextField(blank=True, null=True)),
                ("block_reason", models.TextField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expected_tasks",
                        to="locations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.db.models.functions.datetime.Now,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignee_links",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "TODO"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("BLOCKED", "BLOCKED"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        default=django.db.models.functions.datetime.Now,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("block_reason", models.TextField(blank=True, null=True)),
                (
                    "completion_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANAGER_OVERRIDE", "MANAGER_OVERRIDE"),
                            ("FIELD_EVIDENCE", "FIELD_EVIDENCE"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("completion_note", models.TextField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "assigned_date", "id"],
                name="task_status_date_id_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_by", "status", "assigned_date", "id"],
                name="task_creator_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("title__isnull", False),
                    models.Q(("title__regex", r"^\s*$"), _negated=True),
                ),
                name="task_title_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["TODO", "IN_PROGRESS", "BLOCKED", "COMPLETED"])
                ),
                name="task_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "BLOCKED"),
                        ("block_reason__isnull", False),
                        models.Q(("block_reason__regex", r"^\s*$"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "BLOCKED"), _negated=True),
                        ("block_reason__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="task_block_reason_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completed_at__isnull", False),
                        ("completed_by__isnull", False),
                        ("completion_method", "MANAGER_OVERRIDE"),
                        ("status", "COMPLETED"),
                        ("completion_note__isnull", False),
                        models.Q(("completion_note__regex", r"^\s*$"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "COMPLETED"), _negated=True),
                        ("completed_at__isnull", True),
                        ("completed_by__isnull", True),
                        ("completion_method__isnull", True),
                        ("completion_note__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="task_completion_shape",
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignee",
            index=models.Index(fields=["user", "task"], name="task_assignee_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskassignee",
            constraint=models.UniqueConstraint(
                fields=("task", "user"),
                name="task_assignee_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="taskupdate",
            index=models.Index(fields=["task", "id"], name="task_update_task_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="taskupdate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["TODO", "IN_PROGRESS", "BLOCKED", "COMPLETED"])
                ),
                name="task_update_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskupdate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("note__isnull", True),
                    models.Q(
                        ("note__isnull", False),
                        models.Q(("note__regex", r"^\s*$"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="task_update_note_nonblank",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskupdate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "BLOCKED"),
                        ("block_reason__isnull", False),
                        models.Q(("block_reason__regex", r"^\s*$"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "BLOCKED"), _negated=True),
                        ("block_reason__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="task_update_block_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskupdate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("completion_method", "MANAGER_OVERRIDE"),
                        ("status", "COMPLETED"),
                        ("completion_note__isnull", False),
                        models.Q(("completion_note__regex", r"^\s*$"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("status", "COMPLETED"), _negated=True),
                        ("completion_method__isnull", True),
                        ("completion_note__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="task_update_completion_shape",
            ),
        ),
    ]
