# Generated by Django 5.2.5 on 2026-08-20 07:27

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_completion_idempotency', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_idempotency', to='tasks.task')),
                ('task_update', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_idempotency', to='tasks.taskupdate')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceUpload',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('object_key', models.TextField(unique=True)),
                ('mime', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('UPLOADED', 'UPLOADED'), ('BOUND', 'BOUND'), ('EXPIRED', 'EXPIRED')], db_default='PENDING', default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now)),
                ('expires_at', models.DateTimeField()),
                ('bound_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bound_uploads', to='tasks.taskupdate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_uploads', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_evidence_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.TextField(unique=True)),
                ('mime', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now)),
                ('evidence_upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='task_photo', to='tasks.evidenceupload')),
                ('task_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='tasks.taskupdate')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='task_completion_shape',
        ),
        migrations.RemoveConstraint(
            model_name='taskupdate',
            name='task_update_completion_shape',
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='actual_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_task_updates', to='locations.location'),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='captured_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='captured_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='distance_m',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='gps_quality',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('LOW_ACCURACY', 'LOW_ACCURACY'), ('UNRELIABLE', 'UNRELIABLE')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='location_candidates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, db_default=[], default=list, size=None),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='resolution_method',
            field=models.CharField(blank=True, choices=[('AUTO_SINGLE', 'AUTO_SINGLE'), ('USER_SELECTED', 'USER_SELECTED'), ('GPS_ONLY', 'GPS_ONLY')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='validation_result',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('status', 'COMPLETED'), models.Q(models.Q(('completion_method', 'MANAGER_OVERRIDE'), ('completion_note__isnull', False), models.Q(('completion_note__regex', '^\\s*$'), _negated=True)), ('completion_method', 'FIELD_EVIDENCE'), _connector='OR')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True), ('completed_by__isnull', True), ('completion_method__isnull', True), ('completion_note__isnull', True)), _connector='OR'), name='task_completion_shape'),
        ),
        migrations.AddConstraint(
            model_name='taskupdate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completion_method__isnull', False), ('status', 'COMPLETED'), models.Q(models.Q(('completion_method', 'MANAGER_OVERRIDE'), ('completion_note__isnull', False), models.Q(('completion_note__regex', '^\\s*$'), _negated=True)), models.Q(('accuracy_m__isnull', False), ('captured_at__isnull', False), ('captured_latitude__isnull', False), ('captured_longitude__isnull', False), ('completion_method', 'FIELD_EVIDENCE'), ('gps_quality__isnull', False)), _connector='OR')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completion_method__isnull', True), ('completion_note__isnull', True)), _connector='OR'), name='task_update_completion_shape'),
        ),
        migrations.AddConstraint(
            model_name='completionidempotency',
            constraint=models.UniqueConstraint(fields=('actor', 'task', 'key'), name='task_completion_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='evidenceupload',
            index=models.Index(fields=['task', 'user', 'status'], name='evidence_upload_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceupload',
            index=models.Index(fields=['status', 'expires_at'], name='evidence_upload_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceupload',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), ('size_bytes__lte', 5242880)), name='evidence_upload_size_valid'),
        ),
        migrations.AddConstraint(
            model_name='evidenceupload',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'BOUND'), ('bound_update__isnull', False)), models.Q(models.Q(('status', 'BOUND'), _negated=True), ('bound_update__isnull', True)), _connector='OR'), name='evidence_upload_bound_shape'),
        ),
    ]
