# Generated by Django 5.2.5 on 2026-08-18 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=3)),
                ('work_date', models.DateField()),
                ('recorded_at', models.DateTimeField()),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('captured_latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('captured_longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('accuracy_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('distance_m', models.DecimalField(decimal_places=3, max_digits=12)),
                ('validation_result', models.CharField(max_length=32)),
                ('resolution_method', models.CharField(max_length=32)),
                ('device_metadata', models.JSONField(db_default={}, default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('metadata', models.JSONField(db_default={}, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='attendance.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=3)),
                ('work_date', models.DateField()),
                ('recorded_at', models.DateTimeField()),
                ('outcome', models.CharField(max_length=32)),
                ('captured_latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('captured_longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('accuracy_m', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nearest_distance_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('candidate_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('device_metadata', models.JSONField(db_default={}, default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attendance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempt', to='attendance.attendance')),
                ('nearest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('closed_by_job', models.BooleanField(db_default=False, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opened_session', to='attendance.attendance')),
                ('check_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_session', to='attendance.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'work_date', 'recorded_at', 'id'], name='attendance_timeline_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['IN', 'OUT'])), name='attendance_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('captured_latitude__gte', -90), ('captured_latitude__lte', 90)), name='attendance_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('captured_longitude__gte', -180), ('captured_longitude__lte', 180)), name='attendance_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('accuracy_m__gte', 0)), name='attendance_accuracy_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='attendance_distance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('validation_result', 'INSIDE_GEOFENCE')), name='attendance_validation_inside'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_method__in', ['AUTO_SINGLE', 'USER_SELECTED'])), name='attendance_resolution_valid'),
        ),
        migrations.AddIndex(
            model_name='attendanceanomaly',
            index=models.Index(fields=['reason', 'created_at', 'id'], name='attendance_anomaly_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceanomaly',
            constraint=models.UniqueConstraint(fields=('attendance', 'reason'), name='attendance_anomaly_unique'),
        ),
        migrations.AddConstraint(
            model_name='attendanceanomaly',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['LATE_CHECK_IN', 'EARLY_CHECK_OUT', 'LATE_CHECK_OUT', 'MISSING_CHECK_OUT'])), name='attendance_anomaly_reason_valid'),
        ),
        migrations.AddIndex(
            model_name='attendanceattempt',
            index=models.Index(fields=['user', 'work_date', 'recorded_at', 'id'], name='attendance_attempt_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceattempt',
            index=models.Index(fields=['work_date', 'outcome'], name='attendance_attempt_outcome_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceattempt',
            index=models.Index(fields=['nearest_location', 'outcome'], name='attendance_attempt_nearest_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['IN', 'OUT'])), name='attendance_attempt_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['ACCEPTED', 'WEAK_GPS', 'OUTSIDE_RADIUS', 'LOCATION_CHOICE_REQUIRED', 'INVALID_LOCATION_CHOICE', 'NO_OPEN_SESSION', 'SESSION_ALREADY_OPEN'])), name='attendance_attempt_outcome_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance__isnull', False), ('outcome', 'ACCEPTED')), models.Q(models.Q(('outcome', 'ACCEPTED'), _negated=True), ('attendance__isnull', True)), _connector='OR'), name='attendance_attempt_link_valid'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nearest_distance_m__isnull', True), ('nearest_location__isnull', True)), models.Q(('nearest_distance_m__isnull', False), ('nearest_location__isnull', False)), _connector='OR'), name='attendance_attempt_nearest_pair'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('captured_latitude__gte', -90), ('captured_latitude__lte', 90)), name='attendance_attempt_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('captured_longitude__gte', -180), ('captured_longitude__lte', 180)), name='attendance_attempt_lon_range'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('accuracy_m__gte', 0)), name='attendance_attempt_accuracy_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='attendanceattempt',
            constraint=models.CheckConstraint(condition=models.Q(('nearest_distance_m__isnull', True), ('nearest_distance_m__gte', 0), _connector='OR'), name='attendance_attempt_distance_nonneg'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user', 'work_date', 'id'], name='attendance_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(condition=models.Q(('check_out__isnull', True), ('closed_by_job', False)), fields=('user',), name='uniq_open_session_per_user'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('check_out__isnull', True), ('closed_by_job', False), ('duration_minutes__isnull', True)), models.Q(('check_out__isnull', False), ('closed_by_job', False), ('duration_minutes__isnull', False)), models.Q(('check_out__isnull', True), ('closed_by_job', True), ('duration_minutes__isnull', True)), _connector='OR'), name='attendance_session_shape'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('duration_minutes__gte', 0), _connector='OR'), name='attendance_duration_nonnegative'),
        ),
    ]
