from typing import Protocol


class PasswordService(Protocol):
    def verify(self, encoded: str, raw: str) -> bool: ...

    def encode(self, raw: str) -> str: ...

    def validate(self, username: str, raw: str) -> None: ...

    def generate(self, username: str) -> str: ...
