# Generated by Django 5.2.5 on 2026-08-17 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('schema_version', models.PositiveIntegerField(db_default=1, default=1)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('aggregate_version', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(db_default='', default='', max_length=64)),
                ('correlation_id', models.CharField(db_default='', default='', max_length=64)),
                ('publish_state', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('DEAD_LETTER', 'Dead Letter')], db_default='PENDING', default='PENDING', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['publish_state', 'created_at', 'id'], name='audit_outbox_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('aggregate_type', 'aggregate_id', 'aggregate_version'), name='audit_outbox_aggregate_version_unique'), models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='audit_outbox_schema_version_positive'), models.CheckConstraint(condition=models.Q(('aggregate_version__gte', 1)), name='audit_outbox_aggregate_version_positive'), models.CheckConstraint(condition=models.Q(('publish_state__in', ['PENDING', 'PUBLISHED', 'DEAD_LETTER'])), name='audit_outbox_publish_state_valid')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actor', '-recorded_at'], name='audit_actor_time_idx'), models.Index(fields=['target_type', 'target_id', '-recorded_at'], name='audit_target_time_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
            CREATE FUNCTION audit_reject_log_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit log is immutable';
            END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER audit_log_immutable
            BEFORE UPDATE OR DELETE ON audit_auditlog
            FOR EACH ROW EXECUTE FUNCTION audit_reject_log_mutation();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS audit_log_immutable ON audit_auditlog;
            DROP FUNCTION IF EXISTS audit_reject_log_mutation();
            """,
        ),
    ]
