# Generated by Codex for Feature 012 reliable outbox relay

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="leased_by",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="attempt_count",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="last_error",
            field=models.CharField(blank=True, db_default="", default="", max_length=256),
        ),
        migrations.RemoveIndex(
            model_name="outboxevent",
            name="audit_outbox_pending_idx",
        ),
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(
                fields=["publish_state", "next_attempt_at", "lease_expires_at", "created_at", "id"],
                name="audit_outbox_pending_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("lease_expires_at__isnull", True), ("leased_by__isnull", True))
                    | models.Q(("lease_expires_at__isnull", False), ("leased_by__isnull", False))
                ),
                name="audit_outbox_lease_shape_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="outboxevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("publish_state", "PUBLISHED"), ("published_at__isnull", False))
                    | models.Q(("publish_state", "PUBLISHED"), _negated=True)
                ),
                name="audit_outbox_published_at_required",
            ),
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer", models.CharField(max_length=100)),
                ("event_id", models.UUIDField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["consumer", "processed_at", "id"],
                        name="audit_processed_time_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "event_id"),
                        name="audit_processed_event_unique",
                    )
                ],
            },
        ),
    ]
